### ISSUE TITLE
rename non-Obama specific repositories

### ISSUE THREAD

**Issue by ghost** [ObamaPhony/docs#1]
The only repository that should have the word Obama in the name is the web scraper? everything else should work for any speech.

**Comment by raehik** [comment]
ah, good point. Sure thing, change what you want, I'm fine with fixing
remotes.

**Comment by ghost** [comment]
You don't need to change remotes but probably should do anyway!

**Comment by shymega** [comment]
@saleemrashid so... things like the web API, front-end are in one single repo, and the web scraper and speech gen in another? Shouldn't be too hard to do if so, let me know how it goes so I can do a regex on my Go API to change import paths :-)

**Comment by raehik** [comment]
most parts of the project are gonna be in separate repos because we're all running different languages. The speech generator will be Python piping to Node (correct @saleemrashid ?) and that's separate to the web scraper in VB or w/e.
