### ISSUE TITLE
Organising our notes into directories.

### ISSUE THREAD

**Issue by shymega** [ObamaPhony/docs#2]
In our docs folder for the project so far, we have notes in the root directory. My suggestion is that if our notes become 2 or more, then it might be worth putting notes into a directory structure which resembles the components of our project. 

That way, if the project grows, we have implemented organisation from the start.

**Comment by ghost** [comment]
IMO not enough related docs to do so

**Comment by raehik** [comment]
Move files/folders around if you want, preferably do in a separate branch & merge. ATM there aren't enough files for me to care :)

**Comment by shymega** [comment]
yeah, i do agree with both of you, re not enough files to account for. I'm proposing to keep this issue open for future reference though? cc/ @raehik  @saleemrashid

**Comment by raehik** [comment]
Sure

**Comment by shymega** [comment]
Closing, FoC 2015 is over - no longer relevant.

**Comment by raehik** [comment]
nice cleanup, approved :+1:
