### ISSUE TITLE
Great work - Let me know if you want any advice

### ISSUE THREAD

**Issue by AJCStriker** [ObamaPhony/docs#3]
Hi guys,

Just wanted to drop a line and say I am really impressed you took the time to document your project like this.

Seeing as we do a lot of Node.js based machine learning, feel free to get in touch with me if you want any advice or help if you got stuck on anything!

**Comment by shymega** [comment]
@AJCStriker Cheers man! That's made my day, even with the espressos! Our project is for the Young Rewired State Festival of Code 2015, and I'll bear your offer in mine, and I'm cc/ing my fellow teammates in this for reference. Thanks again for your kind words, ^_^ - cc/ @saleemrashid @raehik

**Comment by AJCStriker** [comment]
@shymega I know what your project is for - I'm judging you in the heats :D

**Comment by shymega** [comment]
@AJCStriker Ah I see! I'm not going to be there for the finals, so I'm keeping my fingers crossed that all goes well (except when I'm coding the rest of this RESTful API :P)

**Comment by AJCStriker** [comment]
@shymega That's a great shame, it seems like you guys have done some really solid work here.

I look forward to meeting your teammates and I'm sure they will represent themselves impeccably.

**Comment by ghost** [comment]
I'm panicking but this stuff should hopefully come together well (crossed fingers being waved madly at computer screen). Thanks for the comments!

**Comment by raehik** [comment]
Thanks for looking at our project! I felt docs would be essential in a project with 4 different languages working in tandem so we knew what input to expect for each module. In good YRS fashion it's gonna be rushed if finished at all :)

**Comment by shymega** [comment]
Closing, FoC 2015 is over.
